source 'https://rubygems.org'

gem 'rails', '4.1.5'
gem 'pg'
gem 'active_model_serializers'

gem 'spring',        group: :development

gem 'sdoc', '~> 0.4.0',          group: :doc

group :development, :test do
  gem 'rspec-rails', '~> 3.0.0'
end
