source 'https://rubygems.org'

gem 'rails', '4.1.5'
gem 'pg'
gem 'active_model_serializers'

gem 'spring',        group: :development

gem 'sdoc', '~> 0.4.0',          group: :doc

gem 'omniauth'
gem 'omniauth-lastfm'
gem 'omniauth-twitter'
gem "omniauth-google-oauth2"
gem 'omniauth-soundcloud', '~> 1.0.0'

gem "figaro"
gem 'pry'
gem 'faraday'

group :development do
 gem 'guard-rspec', require: false
end

group :development, :test do
  gem 'rspec-rails', '~> 3.0.0'
  gem 'shoulda-matchers', require: false
  gem 'vcr'
  gem 'webmock'
end
